<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RMS.Modules.Sales.Infrastructure</RootNamespace>
    <AssemblyName>RMS.Modules.Sales.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="FluentMigrator.Runner" Version="6.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\RMS.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Domain\RMS.Modules.Sales.Domain.csproj" />
    <ProjectReference Include="..\Application\RMS.Modules.Sales.Application.csproj" />
  </ItemGroup>
</Project>
