using System.IO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RMS.Modules.Purchasing.Application.Contracts;

namespace RMS.WPF.ReceiptGeneration;

/// <summary>
/// Generates a printable PDF document for a purchase order so the "Print"
/// action on the Purchase Orders screen produces a real document instead of
/// just a status message.
/// </summary>
public interface IPurchaseOrderDocumentGenerator
{
    Task<string> GenerateAsync(PurchaseOrderReadModel order, string outputDirectory, CancellationToken cancellationToken = default);
}

public sealed class WpfPurchaseOrderDocumentGenerator : IPurchaseOrderDocumentGenerator
{
    public Task<string> GenerateAsync(PurchaseOrderReadModel order, string outputDirectory, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(outputDirectory);
        var fileName = $"PurchaseOrder_{order.PurchaseNumber}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";
        var filePath = Path.Combine(outputDirectory, fileName);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);

                page.Header().Column(header =>
                {
                    header.Item().AlignCenter().Text("Retail Management System").Bold().FontSize(18);
                    header.Item().AlignCenter().Text("Purchase Order").FontSize(12);
                    header.Item().Height(10);
                    header.Item().Text($"PO Number: {order.PurchaseNumber}").FontSize(10);
                    header.Item().Text($"Supplier: {order.SupplierName}").FontSize(10);
                    header.Item().Text($"Order Date: {order.OrderDate:yyyy-MM-dd HH:mm}").FontSize(10);
                    header.Item().Text($"Status: {order.Status}").FontSize(10);
                    if (!string.IsNullOrWhiteSpace(order.SupplierInvoiceNumber))
                        header.Item().Text($"Supplier Invoice: {order.SupplierInvoiceNumber}").FontSize(10);
                });

                page.Content().Column(content =>
                {
                    content.Item().Height(10);
                    content.Item().LineHorizontal(1);
                    content.Item().Height(10);

                    content.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Unit Cost").Bold();
                            header.Cell().Text("Total").Bold();
                        });

                        foreach (var item in order.Items)
                        {
                            table.Cell().Text(item.ProductName);
                            table.Cell().Text(item.Quantity.ToString());
                            table.Cell().Text(item.UnitCost.ToString("F2"));
                            table.Cell().Text(item.TotalCost.ToString("F2"));
                        }
                    });

                    content.Item().Height(10);
                    content.Item().LineHorizontal(1);
                    content.Item().Height(10);

                    content.Item().AlignRight().Text($"SubTotal: {order.SubTotal:F2}");
                    if (order.TaxAmount > 0)
                        content.Item().AlignRight().Text($"Tax ({order.TaxPercentage:F2}%): +{order.TaxAmount:F2}");
                    content.Item().AlignRight().Text($"Total: {order.TotalAmount:F2}").Bold().FontSize(14);

                    if (!string.IsNullOrWhiteSpace(order.Notes))
                    {
                        content.Item().Height(10);
                        content.Item().Text($"Notes: {order.Notes}").FontSize(10);
                    }
                });

                page.Footer().AlignCenter().Text("Generated by RMS — Retail Management System").FontSize(9);
            });
        });

        document.GeneratePdf(filePath);
        return Task.FromResult(filePath);
    }
}
