<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>RMS.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\RMS.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Domain\RMS.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Products\Domain\RMS.Modules.Products.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\Domain\RMS.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sales\Domain\RMS.Modules.Sales.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\Domain\RMS.Modules.Customers.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Purchasing\Domain\RMS.Modules.Purchasing.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Suppliers\Domain\RMS.Modules.Suppliers.Domain.csproj" />
  </ItemGroup>

</Project>
